// ==UserScript==
// @name         Yandex Disk Scraper
// @namespace    http://tampermonkey.net/
// @version      2026-06-10
// @description  Downloads undownloadable PDF, video and text files from Yandex Disk
// @author       wadrodrog
// @match        https://docs.360.yandex.ru/*
// @match        https://docviewer.360.yandex.ru/*
// @match        https://disk.360.yandex.ru/*
// @match        https://docs.yandex.ru/*
// @match        https://docviewer.yandex.ru/*
// @match        https://disk.yandex.ru/*
// @require      https://unpkg.com/jspdf@latest/dist/jspdf.umd.min.js
// @grant        GM.setValue
// @grant        GM.getValue
// @grant        GM.deleteValue
// ==/UserScript==

////////////////////////////////////////////////////////////////////////////////////////////////////
// Observe elements (mostly generated by GPT-5 mini)
////////////////////////////////////////////////////////////////////////////////////////////////////

(async function() {
  'use strict';
  
  console.log('[yds]: Юзерскрипт загружен');
  
  // map selector -> callback(element)
  const WATCHES = [
    { selector: '.resources-action-bar__body', onAdd: el => addButtonInActionBar(el) },
    { selector: '.slider__toolbar', onAdd: el => addButtonInSliderToolbar(el) },
  ];
  const THROTTLE_MS = 120; // coalesce frequent mutation batches

  // simple throttle to run last call after ms
  function throttle(fn, ms) {
    let timer = null;
    let lastArgs = null;
    return function (...args) {
      lastArgs = args;
      if (timer) return;
      timer = setTimeout(() => {
        timer = null;
        fn(...lastArgs);
      }, ms);
    };
  }

  // mark elements already processed to avoid duplicate onAdd calls
  const processed = new WeakSet();

  function handleFound(els, onAdd) {
    for (const el of els) {
      if (!processed.has(el)) {
        processed.add(el);
        try {
          onAdd(el);
        } catch (e) {
          console.error('[yds@handleFound]: onAdd callback error', e);
        }
      }
    }
  }

  // initial scan
  for (const w of WATCHES) {
    const found = Array.from(document.querySelectorAll(w.selector));
    if (found.length) {
      handleFound(found, w.onAdd);
    }
  }

  // helper: find matches inside a node (including the node itself)
  function findMatchesInNode(node, selector) {
    const out = [];
    if (node.nodeType !== Node.ELEMENT_NODE) {
      return out;
    }
    if (node.matches(selector)) {
      out.push(node);
    }
    node.querySelectorAll && node.querySelectorAll(selector).forEach(e => out.push(e));
    return out;
  }

  // MutationObserver callback (throttled)
  const onMutations = throttle((mutations) => {
    // collect roots changed to avoid repeated traversal
    const changedNodes = new Set();
    for (const m of mutations) {
      if (m.type === 'childList') {
        m.addedNodes.forEach(n => changedNodes.add(n));
      } else if (m.type === 'attributes' && m.target) {
        // attribute changes can make an element match; treat target as changed
        changedNodes.add(m.target);
      }
    }
    if (!changedNodes.size) {
      return;
    }

    for (const w of WATCHES) {
      const newly = [];
      for (const node of changedNodes) {
        findMatchesInNode(node, w.selector).forEach(el => newly.push(el));
      }
      if (newly.length) {
        handleFound(newly, w.onAdd);
      }
    }
  }, THROTTLE_MS);

  const observer = new MutationObserver(onMutations);
  observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
    attributes: true, // set true only if attribute changes can cause selector matches
    attributeFilter: undefined
  });

  // expose stop function if needed
  window.__stopMultiSelectorWatcher = () => observer.disconnect();
  
  addStatus();
  
  // Additional detector of action bar (when switching files)
  document.body.addEventListener("mouseup", function() {
    let el = document.querySelector('.resources-action-bar__side-left');
    if (el) {
      setTimeout(() => addButtonInActionBar(el), 100);
    }
  });

  // OLDER
  
  const url = window.location.href;

  if (url.includes("/showcaptcha?")) {
    return;
  }

  // download button in sidebar
  if (url.startsWith("https://docs.")) {
    setTimeout(addDownloadButtonInSidebar, 200);
    setTimeout(async () => {
      if (await GM.getValue("autoDownload", false)) {
        openDocviewerAndStartDownload();
      }
    }, 1000);
    return;
  }

  // download pdf
  if (url.startsWith("https://docviewer.") && window.self === window.top) {
    if (document.title.endsWith(".txt")) {
      setTimeout(addDownloadTxtButton, 2000);
    } else {
      var info = await getFileInfo();
    	downloadPdf(info);
    }
  }
})();

////////////////////////////////////////////////////////////////////////////////////////////////////
// Add buttons
////////////////////////////////////////////////////////////////////////////////////////////////////

// Appears when clicking on files in folder
function addButtonInActionBar(container) {
  console.log("[yds@addButtonInSliderToolbar]: Найдена панель действий над файлом", container);
  
  if (document.getElementById('yds-video-options')) {
    return;
  }
  
  container = document.querySelector(".hover-dropdown .hover-tooltip__tooltip-anchor");
  
  let button = document.createElement("button");
  button.type = "button";
  button.tabindex = 0;
  button.setAttribute("data-react-aria-pressable", true);
  button.ariaLabel = "Скачать";
  button.className = "Orb-Button Orb-Button_onlyIcon Orb-Button_size_md Orb-Button_view_static-light-transparent";
  button.role = "button";
  button.setAttribute("data-testid", "orb-button");
  button.innerHTML = '<div class="Orb-Button-Content"><span class="Orb-Button-LeftSlot"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" focusable="false" fill="none" aria-hidden="true" width="16" height="16" viewBox="0 0 16 16"><path fill="currentColor" d="M2.5 8v1.9c0 1.011.002 1.664.049 2.158.045.471.12.64.172.726a1.5 1.5 0 0 0 .495.495c.085.053.255.127.726.172.494.047 1.147.049 2.158.049h3.8c1.011 0 1.664-.002 2.158-.049.471-.045.64-.12.726-.172a1.5 1.5 0 0 0 .495-.495c.053-.085.127-.255.172-.726.047-.494.049-1.147.049-2.158V8H15v1.9c0 1.964 0 2.946-.442 3.667a3 3 0 0 1-.99.99C12.845 15 11.863 15 9.9 15H6.1c-1.964 0-2.946 0-3.667-.442a3 3 0 0 1-.99-.99C1 12.845 1 11.863 1 9.9V8zm6.25.19 2.22-2.22 1.06 1.06L8 11.06 3.97 7.03l1.06-1.06 2.22 2.22V1h1.5z"></path></svg></span></div>';
  
  let select = document.createElement("select");
  select.id = "yds-video-options";
  select.innerHTML = '<option value="">Не удалось получить форматы для скачивания :(</option>';
  
  // I tested only .mkv
  const filename = getVideoFilename();
  if (filename.endsWith('.mkv') || filename.endsWith('.mp4') || filename.endsWith('.mov') || filename.endsWith('.avi') || filename.endsWith('.webm')) {
  	button.onclick = startVideoDownload;
    
    parseStreams().then(streams => {
      if (streams !== null && !streams.error) {
        select.innerHTML = '';
        let cnt = 1;
        for (let video of streams.data.videos) {
          cnt++;
          if (cnt <= streams.data.videos.length) {
            select.innerHTML += `<option value="${video.url}"${cnt == streams.data.videos.length ? ' selected' : ''}>${video.dimension}</option>`;
          }
        }
      } else {
        console.error("[yds@addButtonInSliderToolbar] Ошибка при получении форматов для скачивания", streams);
      }

      container.insertBefore(select, container.firstChild);
      container.insertBefore(button, container.firstChild);
    });
  }
}

// Appears in video player
function addButtonInSliderToolbar(container) {
  console.log("[yds@addButtonInSliderToolbar]: Найден видеоплеер", container);
  container = container.firstChild;
  
  let select = document.createElement("select");
  select.id = "yds-video-options";
  select.innerHTML = '<option value="">Не удалось получить форматы для скачивания :(</option>';
  
  let button = document.createElement("button");
  button.type = "button";
  button.tabindex = 0;
  button.setAttribute("data-react-aria-pressable", true);
  button.ariaLabel = "Скачать";
  button.className = "Orb-Button Orb-Button_onlyIcon Orb-Button_size_sm Orb-Button_view_static-light-transparent slider__button slider__button_close";
  button.role = "button";
  button.setAttribute("data-testid", "orb-button");
  button.style = "margin-right: 10px;";
  button.innerHTML = '<div class="Orb-Button-Content"><span class="Orb-Button-LeftSlot"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" focusable="false" fill="none" aria-hidden="true" width="16" height="16" viewBox="0 0 16 16"><path fill="currentColor" d="M2.5 8v1.9c0 1.011.002 1.664.049 2.158.045.471.12.64.172.726a1.5 1.5 0 0 0 .495.495c.085.053.255.127.726.172.494.047 1.147.049 2.158.049h3.8c1.011 0 1.664-.002 2.158-.049.471-.045.64-.12.726-.172a1.5 1.5 0 0 0 .495-.495c.053-.085.127-.255.172-.726.047-.494.049-1.147.049-2.158V8H15v1.9c0 1.964 0 2.946-.442 3.667a3 3 0 0 1-.99.99C12.845 15 11.863 15 9.9 15H6.1c-1.964 0-2.946 0-3.667-.442a3 3 0 0 1-.99-.99C1 12.845 1 11.863 1 9.9V8zm6.25.19 2.22-2.22 1.06 1.06L8 11.06 3.97 7.03l1.06-1.06 2.22 2.22V1h1.5z"></path></svg></span></div>';
  button.onclick = startVideoDownload;
  
  parseStreams().then(streams => {
    if (streams !== null && !streams.error) {
      select.innerHTML = '';
      let cnt = 1;
      for (let video of streams.data.videos) {
        cnt++;
        if (cnt <= streams.data.videos.length) {
          select.innerHTML += `<option value="${video.url}"${cnt == streams.data.videos.length ? ' selected' : ''}>${video.dimension}</option>`;
        }
      }
    } else {
      console.error("[yds@addButtonInSliderToolbar] Ошибка при получении форматов для скачивания", streams);
    }
  	
    container.insertBefore(button, container.firstChild);
  	container.insertBefore(select, container.firstChild);
  });
}

// On top of everything
function addStatus() {
  let panel = document.createElement("ul");
  panel.id = "yds-downloads";
  panel.style = "display: none; position: fixed; top: 82px; left: 15px; float: left; z-index: 999; background-color: white; border: 4px solid black; list-style: none; padding: 8px 8px 0 8px;";
  
  document.body.appendChild(panel);
}

////////////////////////////////////////////////////////////////////////////////////////////////////
// Older functions
////////////////////////////////////////////////////////////////////////////////////////////////////

function bulkDownload() {
  const items = document.querySelectorAll(".listing-item_selected");
  const message = "Скачивание нескольких файлов является экспериментальной функцией. Могут быть ошибки, переполнение памяти, капчи. Не все файлы могут успешно скачаться с первого раза.\n\nВ первый раз ваш браузер заблокирует открытие всплывающих окон.\n\nВы уверены, что хотите продолжить?";

  if (items.length > 1 && !window.confirm(message)) {
    return;
  }

  GM.setValue("autoDownload", true);

  for (var item of items) {
    if (!item.querySelector(".clamped-text").innerText.endsWith(".pdf")) {
      continue;
    }
    const event = new MouseEvent("dblclick", { bubbles: true });
    item.dispatchEvent(event);
  }

  setTimeout(() => { GM.deleteValue("autoDownload"); }, 5000 * items.length);
}

function addDownloadButtonInSidebar() {
  const container = document.querySelector(".LeftColumn__Buttons");
  const button = document.createElement("button");

  button.type = "button";
  button.tabindex = 0;
  button.setAttribute("data-react-aria-pressable", true);
  button.className = "Orb-Button Orb-Button_size_md Orb-Button_view_neutral Orb-Button_width_max Docs-Create-Dropdown__Button";
  button.role = "button";
  button.setAttribute("data-testid", "orb-button");
  button.addEventListener("click", openDocviewerAndStartDownload);
  button.innerHTML = '<div class="Orb-Button-Content"><span class="Orb-Button-LeftSlot"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" focusable="false" fill="none" aria-hidden="true" width="16" height="16" viewBox="0 0 16 16"><path fill="currentColor" d="M2.5 8v1.9c0 1.011.002 1.664.049 2.158.045.471.12.64.172.726a1.5 1.5 0 0 0 .495.495c.085.053.255.127.726.172.494.047 1.147.049 2.158.049h3.8c1.011 0 1.664-.002 2.158-.049.471-.045.64-.12.726-.172a1.5 1.5 0 0 0 .495-.495c.053-.085.127-.255.172-.726.047-.494.049-1.147.049-2.158V8H15v1.9c0 1.964 0 2.946-.442 3.667a3 3 0 0 1-.99.99C12.845 15 11.863 15 9.9 15H6.1c-1.964 0-2.946 0-3.667-.442a3 3 0 0 1-.99-.99C1 12.845 1 11.863 1 9.9V8zm6.25.19 2.22-2.22 1.06 1.06L8 11.06 3.97 7.03l1.06-1.06 2.22 2.22V1h1.5z"></path></svg></span><span class="Orb-Button-Text"><div class="Orb-Button-Label">Скачать</div></span></div>';

  container.appendChild(button);
}

function openDocviewerAndStartDownload() {
  const iframe = document.querySelector("iframe");
  window.open(iframe.src, "_blank");
  //setTimeout(window.close, 5000);
}

async function getFileInfo() {
  var info = {};

  var container = null;
  while (container === null) {
    await new Promise(resolve => setTimeout(resolve, 1000));
    container = document.querySelector(".js-doc-page > div");
  }

  const htmlimage = container.shadowRoot.querySelector(".page_pdf > div > div > img");
  const filename = document.querySelector("#app > .embed-docs .Orb-Text");
  const pageCounter = document.querySelector("span[class^=pageCounter]");

  info.filename = filename.innerText;
  info.pages = pageCounter.innerText.split(" из ")[1];

  info.url = "";

  for (var param of htmlimage.src.split("&")) {
    if (param.startsWith("name=bg-")) {
      continue;
    }
    if (param.startsWith("width=") || param.startsWith("height=")) {
      var part = param.split("=");
      info[part[0]] = parseInt(part[1]);
      continue;
    }
    info.url += param + "&";
  }

  info.orientation = info.width > info.height ? "landscape" : "portrait";
  const scaleFactor = Math.max(info.width, info.height) / Math.min(info.width, info.height);
  if (Math.abs(scaleFactor - 16 / 9) < 0.01) {
    info.width = info.orientation == "landscape" ? 1920 : 1080;
    info.height = info.orientation == "landscape" ? 1080 : 1920;
  } else if (Math.abs(scaleFactor - Math.sqrt(2)) < 0.01) {
    info.width = info.orientation == "landscape" ? 2248 : 1588;
    info.height = info.orientation == "landscape" ? 1588 : 2248;
  }

  info.url += "width=" + info.width;
  info.url += "&height=" + info.height;
  info.url += "&name=";

  return info;
}

function downloadPdf(info) {
  document.querySelector("#app").style.display = "none";

  const progressBar = document.createElement("progress");
  const progressBarLabel = document.createElement("div");
  progressBarLabel.className = "orbHeadTitle_BHee2H328gclV_nqwCi_ heading-sm";
  progressBarLabel.innerText = `Скачивание страниц... (0/${info.pages})`;
  progressBarLabel.style.padding = "20px";
  progressBar.style.marginLeft = "20px";
  progressBar.max = info.pages * 2;
  progressBar.value = 0;
  document.body.appendChild(progressBarLabel);
  document.body.appendChild(progressBar);

  GM.deleteValue("autoDownload");

  const pdf = new jspdf.jsPDF({
    orientation: info.orientation,
    unit: "px",
    format: [info.width, info.height],
      compress: true,
      hotfixes: ["px_scaling"]
  });

  var threads = [];
  var failed = [];
  var fails = 0;

  for (var i = 0; i < info.pages; i++) {
    threads.push(
      fetch(info.url + `bg-${i}.png`)
      .then(response => {
        if (!response.ok || response.url.includes("/showcaptcha?")) {
          fails++; // TODO: figure out how to block variable
          return null;
        }
        progressBar.value++;
        progressBarLabel.innerText = `Скачивание страниц... (${progressBar.value}/${info.pages})`;
        return response.bytes();
      })
    );
  }

  Promise.all(threads)
  .then(async (images) => {
    if (fails > 0 && window.confirm(`Некоторые страницы (${fails}) не удалось скачать из-за капчи.\n\nКак можно избежать капчи:\n- Перезагружать страницу несколько раз\n- Чистить куки (заходить с режима инкогнито или с других браузеров)\n- Войти в аккаунт Яндекса\n\nПерезагрузить страницу и попробовать снова?`)) {
      window.location.reload();
    }

    progressBarLabel.innerText = `Формирование документа... (0/${info.pages})`;

    for (var i = 0; i < images.length; i++) {
      if (i > 0) { // first page already added
        pdf.addPage([info.width, info.height], info.orientation);
      }
      if (images[i] === null) {
        failed.push(i + 1);
      } else {
        pdf.addImage(images[i], "PNG", 0, 0, info.width, info.height);
      }
      progressBar.value++;
      progressBarLabel.innerText = `Формирование документа... (${i + 1}/${info.pages})`;
      await new Promise(resolve => setTimeout(resolve, 0)); // updates page after addImage hang
    }
  })
  .then(() => {
    if (failed.length > 0) {
      alert("Внимание, некоторые страницы не удалось сохранить: " + failed.join(", "));
    }
    progressBarLabel.innerText = `Сохранение документа...`;
    pdf.save(info.filename);
  })
  .then(() => setTimeout(window.close, 5000));
}

/* TXT downloader */

function addDownloadTxtButton() {
	const buttonContainer = document.querySelector('.header__side-left');
  const button = document.createElement("button");
  
  button.innerText = "Скачать";
  button.addEventListener("click", parseTxt);
  
  buttonContainer.appendChild(button);
}

function parseTxt() {
	//const titleElement = document.querySelector('[class^="titleWrapper_"]');
  const pagesElement = document.querySelector('[class^="pages_"]').childNodes[1].childNodes;
  
  let title = document.title; //titleElement.childNodes[0].innerText;
  let contents = "";
  
  for (let pageElement of pagesElement) {
    let root = pageElement.childNodes[0].childNodes[0].shadowRoot;
    let blocks = root.querySelector(".page_text > .b1").childNodes;
    
    for (let block of blocks) {
      contents += block.innerText + "\n\n";
    }
  }
  contents = contents.slice(0, -2);
  
  downloadTxt(title, contents);
  console.log(title);
  console.log(contents);
}

function downloadTxt(filename, text) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  URL.revokeObjectURL(url);
}

////////////////////////////////////////////////////////////////////////////////////////////////////
// Video downloader
////////////////////////////////////////////////////////////////////////////////////////////////////

function getVideoFilename() {
  const title = document.querySelector(".resources-info-dropdown__text-wrap .hover-tooltip__tooltip-anchor span");
  if (title === null) {
    return location.href.substring(location.href.lastIndexOf('/') + 1, location.href.length);
  }
  return title.innerText;
}

async function parseStreams() {
  const dataContainer = document.getElementById("store-prefetch");
  const data = JSON.parse(dataContainer.firstChild.textContent);
  const sk = data.environment.sk;
  const folderId = data.rootResourceId;
  const hash = data.resources[folderId].hash;
  const filename = getVideoFilename();
  const requestBody = `%7B%22hash%22%3A%22${hash.replaceAll('+', '%2B')}%3A%2F${filename}%22%2C%22sk%22%3A%22${sk}%22%7D`;
  const apiEndpoint = 'https://disk.360.yandex.ru/public/api/get-video-streams';
  
  return fetch(apiEndpoint, {
    method: 'POST',
    headers: {'Content-Type': 'text/plain'},
    body: requestBody
  }).then(response => {
    if (!response.ok) {
      console.error('[yds@parseStreams]: Не удалось получить список форматов для скачивания');
      return null;
    }
    return response.json();
  });
}

function startVideoDownload() {
  const format = document.getElementById('yds-video-options');
  const filename = getVideoFilename();
  
  addToQueue(filename, format.selectedOptions[0].innerText);
  
  downloadVideo(format.value, filename).then(result => {
    if (result) {
      console.log('[yds@startVideoDownload]: Успешно скачано!');
    } else {
      console.log('[yds@startVideoDownload]: Не удалось скачать :(');
      updateStatus(filename, 'Не удалось скачать :(');
    }
    setTimeout(() => removeFromQueue(filename), 3000);
  });
}

async function downloadVideo(m3u8Url, filename) {
  if (!m3u8Url) {
    console.error('[yds@downloadVideo]: No m3u8 URL');
    return false;
  }
  
  console.log('[yds@downloadVideo]: Start downloading video...', m3u8Url);
  
  const segments = await parsem3u8(m3u8Url);
  const totalSegments = segments.length;
  if (totalSegments === 0) {
    console.error('[yds@downloadVideo]: No segments found!');
    return false;
  }
  console.log('[yds@downloadVideo]: Found ' + totalSegments + ' segments');
  
  const buffer = await downloadVideoSegments(segments, filename);
  if (buffer === null) {
    console.error('[yds@downloadVideo]: Unable to download segments!');
    return false;
  }
  
  console.log('[yds@downloadVideo]: Writing input file...');
  updateStatus(filename, 'Сохранение файла...');
  const blob = new Blob([buffer], { type: 'video/' + filename.substring(filename.lastIndexOf('.') + 1, filename.length) });
  
  console.log('[yds@downloadVideo]: Triggering download...');
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(a.href);
  
  console.log('[yds@downloadVideo]: Done!');
  updateStatus(filename, 'Готово!');
  return true;
}

async function parsem3u8(url) {
  const contents = await downloadText(url);
  if (contents === null) {
    console.error('[yds@parsem3u8]: Unable to get m3u8 contents', url);
    return [];
  }
  const base = url.substring(0, url.lastIndexOf('/') + 1);
  
  return contents
    .split('\n')
    .map(s => s.trim())
    .filter(l => l.includes('.ts?'))
  	.map(s => base + s);
}

async function downloadText(url) {
  return await fetch(url)
  	.then(response => {
    	if (!response.ok) {
        console.error('[yds@downloadText]: Unable to download text', url, response);
        return null;
      }
    	return response.text();
  	});
}

async function downloadVideoSegments(segments, filename) {
  const parts = [];
  const totalSegments = segments.length;
  let totalBytes = 0;
  let threads = [];
  let failed = false;
  let downloadedSegments = 0;
  updateProgressMax(filename, totalSegments);
  
  for (let currentSegment = 0; currentSegment < totalSegments; currentSegment++) {
    threads.push(
      fetch(segments[currentSegment])
      	.then(response => {
          if (!response.ok) {
            console.error(`[yds@downloadVideoSegments]: Unable to download segment ${currentSegment}/${totalSegments}`);
            failed = true;
            return null;
          }
          downloadedSegments++;
          console.log(`[yds@downloadVideoSegments]: ${downloadedSegments}/${totalSegments} downloaded`);
          updateStatus(filename, `Скачивание (${Math.round(downloadedSegments / totalSegments * 100)}%)`);
          updateProgressValue(filename, downloadedSegments);
          return response.arrayBuffer();
        })
    );
  }
  
  return await Promise.all(threads)
    .then(async (arrayBuffers) => {
      if (failed && window.confirm("Некоторые сегменты не удалось скачать. Итоговое видео может быть битым. Попробовать скачать заново?")) {
        window.location.reload();
      }

      console.log('[yds@downloadVideoSegments]: Saving downloaded segments...');
    	updateStatus(filename, 'Завершение загрузки...');

      for (const ab of arrayBuffers) {
        parts.push(new Uint8Array(ab));
        totalBytes += ab.byteLength;
      }
    })
    .then(() => {
    	const out = new Uint8Array(totalBytes);
      let off = 0;
      for (const p of parts) {
        out.set(p, off);
        off += p.length;
      }
      console.log('[yds@downloadVideoSegments]: All segments downloaded, total size: ' + totalBytes);
    	return out;
    });
}

function addToQueue(filename, format) {
  let queue = document.getElementById('yds-downloads');
  
  let item = document.createElement('li');
  item.id = btoa(filename).replaceAll('=', '_');
  item.style = "margin-bottom: 8px;";
  item.innerHTML = `<span>${filename} @ ${format}</span><progress style="margin: 0 8px 0 8px;"></progress><span class="yds-status">Начало скачивания...</span>`;
  
  queue.appendChild(item);
  queue.style.display = "";
}

function updateStatus(filename, message) {
  let id = btoa(filename).replaceAll('=', '_');
  document.querySelector(`#${id} .yds-status`).innerText = message;
}

function updateProgressMax(filename, max) {
  let id = btoa(filename).replaceAll('=', '_');
  let p = document.querySelector(`#${id} progress`).max = max;
}

function updateProgressValue(filename, value) {
  let id = btoa(filename).replaceAll('=', '_');
  let p = document.querySelector(`#${id} progress`).value = value;
}

function removeFromQueue(filename) {
  let queue = document.getElementById('yds-downloads');
  let id = btoa(filename).replaceAll('=', '_');
  document.querySelector(`#${id}`).remove();
  if (queue.children.length == 0) {
    queue.style.display = "none";
  }
}
